### PR TITLE
Master

### PR DESCRIPTION
**Pull request by vk3il**
Added 630m band definitions

### CODE REVIEW

**Comment by camilstaps** [comment]
Hi David,
I'm not sure what happened here. There was an update to master with old code, which I reverted. This PR is to merge master into Auto-band-v2. If that is what you intend to do, go ahead (since that is 'your' branch), but the normal direction would be opposite, i.e., you work on the auto band feature and want to add it to master. There are some commits in Auto-band-v2 which are not in master; see https://github.com/camilstaps/SODA-POP-source/compare/master...568dd271c573402be9ca1bf0bb61d337f71c9c2e; we can add those to master if you want (except the part where it changes settings.h). But nowhere can I find anything about 630m band definitions about which you write above. Let me know what you'd like to happen :)

**Comment by vk3il** [comment]
Hi Camil,

Sorry, I think that's my very infrequent use of Git and getting confused as
to what I was doing. The only change I was trying to make was to add band
definitions for 630m as I'm having a go at getting a 630m module working.
The commits in my branch probably should be merged into the master as they
were fixing up some issues with the keying waveform being truncated before
the anti-click tail had time to complete. I added the 630m band definitions
to the Master and committed after I did the pull request. It's showing up
OK on github for me now. Only file modified was bands.h.

73

David
VK3IL

ᐧ

**Comment by camilstaps** [comment]
No problem! I have added the changes to the master branch now, and removed the Auto-band-v2 branch which did not contain any new code any more, hopefully that helps reduce confusion in the future :) In any case it's great to see you're still developing extra bands, and thanks for putting them online for others to use.

73, Camil PA5ET

**Comment by vk3il** [comment]
Thanks Camil. I agree, I think we only need the Master now as I don't
expect many future changes. I still have my eye on a 6m module, but that's
quite a bit more design effort and a new PCB. The 630m version is just new
Ls and Cs. Remains to be seen whether 5W CW is useful on 630m with the
rather inefficient antennas!

73

David
VK3IL

ᐧ

**Pull request closed without merging**
